FROM postgres:latest

ENV POSTGRES_PASSWORD=password
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=devops_exam_db
ENV POSTGRES_HOST_METHOD=md5
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5432

EXPOSE 5432

COPY init_database.sql /docker-entrypoint-initdb.d/