FROM postgres:latest

ENV POSTGRES_PASSWORD=password_test
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=database_test
ENV POSTGRES_HOST_METHOD=md5
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5432

EXPOSE 5432

COPY start.sql /docker-entrypoint-initdb.d/